DELETE http://localhost:3003/api/blogs/61c8ba4ac45cd706b142d961
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2MWM4YmExZmM0NWNkNzA2YjE0MmQ5NWIiLCJpYXQiOjE2NDA1NDQ4MTF9.wL-dN9TAFaiKwoM5Mcz3cnPrTbVnzTc2TCjOZOoTKVg